### ISSUE TITLE
Think of a control plan

### ISSUE THREAD

**Issue by samollari** [LongMetal-Robotics/Infinite-Recharge#22]
This isn't something one person can work on - we should use this issue as a thread to brainstorm ideas and note conversations with the drive team (Matt S., @AndreasDuma).  
We need to think of how each part is going to be controlled, for example:
- Do we still want to use Curvature drive?
- What buttons will do what?

**Comment by EarlJr53** [comment]
I will make the suggestion (as I did during kickoff when people said they wanted the shooter to be able to aim side to side) that we add a button (potentially one of the triggers on the driver's joysticks) that activates a "slow turning" mode, to allow for more accurate steering to get through narrower spaces or manual aiming if something happens to the LimeLight.

**Comment by EarlJr53** [comment]
I'm hoping to have a bit of a meeting with drive team during drive practice tomorrow to talk about controls and try to get some of this stuff nailed down. I'll send Lee an email to see what he says. @i-am-gizm0 @AndreasDuma @achkvina will you guys be at drive practice on Wednesday?

**Comment by EarlJr53** [comment]
Here's a document for control ideas. I will try to draw up an outline and flesh it out over the next few days. [https://docs.google.com/document/d/1p3tgwfI0388d5cF5c7i890YLaSrX2-kR-b7R0yvfRA8/edit?usp=sharing](https://docs.google.com/document/d/1p3tgwfI0388d5cF5c7i890YLaSrX2-kR-b7R0yvfRA8/edit?usp=sharing)

**Comment by EarlJr53** [comment]
Alrighty, we have a full control plan pretty well fleshed out, it's in that Google Doc. The most reliable section is in the last 2 pages. If you are writing any code for part of the robot and are wondering how it will be controlled, I would be the person to ask.

**Comment by EarlJr53** [comment]
![image](https://user-images.githubusercontent.com/57816752/74564313-c5008880-4f3c-11ea-8a11-11d8b1f0d027.png)
This boi be handy

**Comment by EarlJr53** [comment]
I'd say this is done, at long last :)
