### ISSUE TITLE
Refactor Constants

### ISSUE THREAD

**Issue by samollari** [LongMetal-Robotics/Infinite-Recharge#36]
Currently, [`Constants.java`](https://github.com/LongMetal-Robotics/Infinite-Recharge/tree/master/src/main/java/org/longmetal/Constants.java) isn't really organized. Someone should go in and group everything together that goes together: everything drive train together, everything intake together, etc.

**Comment by Sky14r** [comment]
began in _constants-refactorization_. needs a look-over, and some judging as to whether or not the written system should be kept,,, but right now i think it looks okay.

**Comment by EarlJr53** [comment]
Done! (i think)
