### ISSUE TITLE
Get Target Distance from Limelight

### ISSUE THREAD

**Issue by samollari** [LongMetal-Robotics/Infinite-Recharge#40]
Limelight has a [great article](http://docs.limelightvision.io/en/latest/cs_estimating_distance.html) about getting the distance to a target using a limelight. @EarlJr53's `ShooterFormula` expects a distance in meters so we can use this to feed it values we need.

**Comment by samollari** [comment]
Important for the calculations:
On our bot, the lens of the Limelight is ~1'11" above the ground (thanks @EarlJr53)

~~Also, the camera is currently mounted at an angle of... 0&deg;. It's parallel with the horizon. We may need to change that depending on how high (of an angle) we can shoot the balls.~~ ~~@EarlJr53 noted that the whole shooter was angled so we need to get that angle~~
The camera is ~11° above horizontal currently

**Comment by EarlJr53** [comment]
@i-am-gizm0 the limelight camera is no longer mounted at 0 degrees, as they angled the whole shooter. I will find a value for that angle and add it to this comment.

**Comment by EarlJr53** [comment]
In addition to getting the distance value, we need to get the data to align the drivetrain to the target. This was mentioned in #34 , but as I clean up the Issues list, I want to add it to here.

**Comment by EarlJr53** [comment]
The alignment, as mentioned in the previous comment, is done, apart from some fine tuning. The shooter distance readings' first draft is done, and I hope to test it once the shooter is back on the robot.

**Comment by EarlJr53** [comment]
I just implemented this into <master>, so we will test this afternoon, and then it should be good!
