### ISSUE TITLE
Add Shuffleboard elements

### ISSUE THREAD

**Issue by samollari** [LongMetal-Robotics/Infinite-Recharge#52]
## Status Boxes
- [x] Endgame (bool)
- [x] RPM (num)
  - [ ] OK for shooting speed (temporary bool)
## Enablers
- [x] Control Panel

**Comment by EarlJr53** [comment]
What is 'OK for Shooting Speed'?

**Comment by EarlJr53** [comment]
Theoretically, the last part will work, but I need Limelight values first. This isn't super important though, so oh well
