### ISSUE TITLE
A bunch of improvements

### ISSUE THREAD

**Issue by samollari** [LongMetal-Robotics/Infinite-Recharge#62]
There are a couple of things we need to fix:
- [x] Shooter idle: the shooter should idle at 1000RPM when it isn't doing anything else but currently it just stops
- [x] Singulator idle: the shooter should idle spinning backward slowly to keep the power cells out of the shooter
- [x] At some point, we should also try to increase the speed of the robot because it's a little slow right now.

**Comment by EarlJr53** [comment]
I fixed both idles, the singulator and the shooter, and we can test them after school today. The drivetrain issues should also be worked on today.

**Comment by samollari** [comment]
The robot perpetually thought the climb was up so it was limiting its speed. It's a bit faster now
