### ISSUE TITLE
New things to add

### ISSUE THREAD

**Issue by samollari** [LongMetal-Robotics/Infinite-Recharge#63]
Some things that we need to add at some point:
- [x] PID for alignment: Lining up using the Limelight isn't super accurate since it won't turn much when it is already close. We should have PID for lining up with the Limelight
- [x] Run the shooter backwards: The power cells get stuck in the shooter because the singulator idles forward (in #62), so we should let it run backward to get it out

**Comment by EarlJr53** [comment]
I added a control to run the shooter + singulator backwards manually. I also added an automatic reverse function for the drivetrain to shoot into the lower port.

**Comment by samollari** [comment]
I am somewhere near halfway through tuning the PID loop so I'll just close this issue
