### ISSUE TITLE
Create utility classes

### ISSUE THREAD

**Issue by samollari** [LongMetal-Robotics/Infinite-Recharge#9]
We created a few classes in [LongMetal-Robotics/ShowBot](https://github.com/LongMetal-Robotics/Showbot) that are useful for many situations. We should copy them over to this repo.
They are all in `org.longmetal.util`:
- [x] Dual
- [x] Listener
- [x] Math

**Comment by danke7127** [comment]
Hey Sam we did the thing. and we did not (probably) mess it up.
